# Generated by Django 3.1 on 2020-08-31 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UmoneyReq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('comment', models.CharField(blank=True, default='', max_length=100)),
                ('card_number', models.CharField(blank=True, default='', max_length=16)),
                ('card_algorithm_id', models.CharField(blank=True, default='', max_length=2)),
                ('card_keyset_v', models.CharField(blank=True, default='', max_length=2)),
                ('card_transaction_seq_number', models.CharField(blank=True, default='', max_length=10)),
                ('card_random_number', models.CharField(blank=True, default='', max_length=16)),
                ('card_balance', models.CharField(blank=True, default='', max_length=10)),
                ('topup_amount', models.CharField(blank=True, default='', max_length=10)),
                ('sign1', models.CharField(blank=True, default='', max_length=8)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
