# Generated by Django 3.1 on 2020-09-01 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('umoney', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UmoneyReq',
            new_name='TopupReq',
        ),
    ]
