# Generated by Django 3.1 on 2020-09-02 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umoney', '0002_auto_20200901_0158'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectionReq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('pos_id', models.CharField(blank=True, default='', max_length=64)),
                ('terminal_id', models.CharField(blank=True, default='', max_length=64)),
                ('authentication_id', models.CharField(blank=True, default='', max_length=64)),
            ],
        ),
    ]
