# Generated by Django 3.1 on 2020-09-04 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umoney', '0003_connectionreq'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectionreq',
            name='merchant_info_terminal_id',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='connectionreq',
            name='message_type_id',
            field=models.CharField(blank=True, default='', max_length=4),
        ),
        migrations.AddField(
            model_name='connectionreq',
            name='primary_bit_map',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='connectionreq',
            name='processing_code',
            field=models.CharField(blank=True, default='', max_length=6),
        ),
        migrations.AddField(
            model_name='connectionreq',
            name='transaction_unique',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
        migrations.AddField(
            model_name='connectionreq',
            name='transmission_datetime',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
