# Generated by Django 3.1 on 2020-09-04 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umoney', '0005_connectionresp'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectionreq',
            name='vsam_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='connectionresp',
            name='vsam_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
