# Generated by Django 3.1 on 2020-09-04 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umoney', '0007_auto_20200904_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopupResp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('comment', models.CharField(blank=True, default='', max_length=100)),
                ('message_type_id', models.CharField(blank=True, default='', max_length=4)),
                ('primary_bit_map', models.CharField(blank=True, default='', max_length=16)),
                ('processing_code', models.CharField(blank=True, default='', max_length=6)),
                ('transmission_datetime', models.CharField(blank=True, default='', max_length=10)),
                ('transaction_unique', models.CharField(blank=True, default='', max_length=12)),
                ('terminal_id', models.CharField(blank=True, default='', max_length=40)),
                ('request_data_len', models.CharField(blank=True, default='', max_length=3)),
                ('tran_type', models.CharField(blank=True, default='', max_length=2)),
                ('card_number', models.CharField(blank=True, default='', max_length=16)),
                ('vsam_tran_seq_num', models.CharField(blank=True, default='', max_length=10)),
                ('card_balance', models.CharField(blank=True, default='', max_length=10)),
                ('topup_amount', models.CharField(blank=True, default='', max_length=10)),
                ('sign2', models.CharField(blank=True, default='', max_length=8)),
                ('deposit_balance', models.CharField(blank=True, default='', max_length=10)),
                ('payment_method', models.CharField(blank=True, default='', max_length=1)),
                ('sign1', models.CharField(blank=True, default='', max_length=8)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
