# Generated by Django 3.1 on 2020-09-04 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umoney', '0008_topupresp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topupreq',
            old_name='request_data_len',
            new_name='result_message_len',
        ),
        migrations.AddField(
            model_name='topupreq',
            name='result_message_data',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
