# Generated by Django 3.1 on 2020-09-06 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umoney', '0010_auto_20200904_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='topupresp',
            name='response_code',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
    ]
