# Generated by Django 3.1 on 2020-09-06 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umoney', '0011_topupresp_response_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositBalanceInquiryReq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('comment', models.CharField(blank=True, default='', max_length=100)),
                ('message_type_id', models.CharField(blank=True, default='', max_length=4)),
                ('primary_bit_map', models.CharField(blank=True, default='', max_length=16)),
                ('processing_code', models.CharField(blank=True, default='', max_length=6)),
                ('transmission_datetime', models.CharField(blank=True, default='', max_length=10)),
                ('transaction_unique', models.CharField(blank=True, default='', max_length=12)),
                ('terminal_id', models.CharField(blank=True, default='', max_length=40)),
                ('request_data_len', models.CharField(blank=True, default='', max_length=3)),
                ('pos_id', models.CharField(blank=True, default='', max_length=64)),
                ('encrypted_vsam_id', models.CharField(blank=True, default='', max_length=32)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='DepositBalanceInquiryResp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('comment', models.CharField(blank=True, default='', max_length=100)),
                ('message_type_id', models.CharField(blank=True, default='', max_length=4)),
                ('primary_bit_map', models.CharField(blank=True, default='', max_length=16)),
                ('response_code', models.CharField(blank=True, default='', max_length=2)),
                ('result', models.CharField(blank=True, default='', max_length=2)),
                ('result_message_len', models.CharField(blank=True, default='', max_length=3)),
                ('result_message_data', models.CharField(blank=True, default='', max_length=64)),
                ('processing_code', models.CharField(blank=True, default='', max_length=6)),
                ('transmission_datetime', models.CharField(blank=True, default='', max_length=10)),
                ('transaction_unique', models.CharField(blank=True, default='', max_length=12)),
                ('terminal_id', models.CharField(blank=True, default='', max_length=40)),
                ('request_data_len', models.CharField(blank=True, default='', max_length=3)),
                ('pos_id', models.CharField(blank=True, default='', max_length=64)),
                ('encrypted_vsam_id', models.CharField(blank=True, default='', max_length=32)),
                ('deposit_balance', models.CharField(blank=True, default='', max_length=32)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
