# Generated by Django 3.1 on 2020-09-06 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('umoney', '0012_depositbalanceinquiryreq_depositbalanceinquiryresp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depositbalanceinquiryresp',
            name='encrypted_vsam_id',
        ),
        migrations.RemoveField(
            model_name='depositbalanceinquiryresp',
            name='request_data_len',
        ),
        migrations.RemoveField(
            model_name='depositbalanceinquiryresp',
            name='result',
        ),
    ]
