# Generated by Django 3.1 on 2020-09-09 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umoney', '0017_auto_20200908_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='topupcheckresp',
            name='vsam_id',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='topupresp',
            name='vsam_id',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
    ]
