# Generated by Django 3.1 on 2020-09-09 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umoney', '0019_auto_20200909_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='topupresp',
            name='vsam_id_hex',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
