# Generated by Django 3.1 on 2020-09-10 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umoney', '0020_topupresp_vsam_id_hex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topupcheckreq',
            name='sign2',
        ),
        migrations.AddField(
            model_name='topupcheckreq',
            name='payment_id',
            field=models.CharField(blank=True, default='', max_length=36),
        ),
        migrations.AddField(
            model_name='topupcheckresp',
            name='payment_id',
            field=models.CharField(blank=True, default='', max_length=36),
        ),
        migrations.AddField(
            model_name='topupreq',
            name='payment_id',
            field=models.CharField(blank=True, default='', max_length=36),
        ),
        migrations.AddField(
            model_name='topupresp',
            name='payment_id',
            field=models.CharField(blank=True, default='', max_length=36),
        ),
    ]
