# Generated by Django 3.1 on 2020-09-10 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('umoney', '0021_auto_20200910_0403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topupcheckresp',
            name='sign2',
        ),
    ]
