# Generated by Django 3.1.1 on 2020-10-19 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umoney', '0022_remove_topupcheckresp_sign2'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionaggregationinquiryresp',
            name='closing_date',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='transactionaggregationinquiryresp',
            name='pos_id',
            field=models.CharField(blank=True, default='HIPAYPOSID12345678', max_length=64),
        ),
    ]
